---
title: "Final"
output: html_document
---

```{r setup, include=FALSE}

# THIS DOCUMENT IS NOT INTENDED TO BE VIEWED. IT IS SIMPLY AN ORGANIZED
#   WAY OF CREATING AND SAVING THE GRAPHS FOR THE SHINY APP

# After the graphs are created here, their data is saved as an RDS and 
#   the code used to create them is copied and used in the shiny app

knitr::opts_chunk$set(echo = TRUE)

# Load Required Libraries

library(tidyverse)
library(dplyr)
library(ggplot2)
library(stringr)

```

```{r p1, echo = FALSE, warning = FALSE, include = FALSE}

# DOwnload data from Raj Chetty's Dataset "The American Dream"

baseline_estimates <- read_csv("data/table1_national_absmob_by_cohort_parpctile.csv")


```

```{r p2, echo = FALSE, warning = FALSE}

### CHART 1 ###
# Goal in this chart is to recreate the chart from the dataset

# Select the elements that we will use to plot in chart 1

simple_plot <- baseline_estimates %>% select(cohort, cohort_mean)

# Use ggplot to plot the chart. Use a combination of line and
#   point plots to createe the desired aesthetic effect
# Use the ggplot theme option and axis titles to correctly style
#   the graph

ggplot(simple_plot, aes(x = cohort, y = cohort_mean)) + 
  geom_line(size = .75) + geom_point(size = 3) + 
  coord_cartesian(ylim = c(.48, 1.00)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Child's Year of Birth",
       y = "Pct. of Children Earning More than their Parents",
       title = "Percent of Children Earning More than Their Parents, by Year of Birth") +
  theme_bw() + 
  theme(axis.title.x = element_text(colour = "#9d9eac"),
        axis.title.y = element_text(colour = "#9d9eac"))

# save the data to an RDS file for use in Shiny

write_rds(simple_plot, "./shiny/chart1.rds")

```

```{r}

### Chart 2 ###

# Splitting Data up by income bracket: who is making more $$?
# Some inspiration from stack overflow

grouped_plot <- baseline_estimates %>% 
  
  # Used to allow the rows to be acted upon individually
  
   rowwise %>% 
  
  # Gather all of the different columns from percentiles 1 -> 100, calculate
  #   the sums across all percentiles and the means. This will allow us to 
  #   test the accuracy of our data compared to the previous dataset from
  #   chart 1
  
   do(as.data.frame(.) %>% { 
      subs <- select(., abs_mob_pos_par_p1:abs_mob_pos_par_p100)
      mutate(., Sum = subs %>% sum,
                Mean = subs %>% mean) 
      } ) %>%
   ungroup %>% 
  mutate(Sum = round(Sum / 100, 3)) %>% 
  select(cohort, Sum, cohort_mean, par_frac0)

# Plot results to show difference between the 2 previous graphs

ggplot(grouped_plot, aes(x = cohort)) + 
  geom_line(aes(y = cohort_mean), size = .75) + 
  geom_line(aes(y = Sum), size = .75) + 
  coord_cartesian(ylim = c(.40, 1.00)) +
  scale_y_continuous(labels = scales::percent)

# Plotting all 100 different datasets on 1 graph
# Use the gather() function to tidy data

tidy_data <- baseline_estimates %>% 
  gather("income_bracket", "probability_exceed", abs_mob_pos_par_p1:abs_mob_pos_par_p100)

# PLOT FOR EACH INDIVIDUAL INCOME BRACKET
# Use ggplot to plot all groups onto a graph

ggplot(tidy_data, aes(x = cohort, y = probability_exceed, group = income_bracket)) + 
  geom_line(size = .75, alpha = .1) + 
  geom_point(size = 2, alpha = .1) + 
  coord_cartesian(ylim = c(.0, 1.00)) +
  scale_y_continuous(labels = scales::percent)

# Create a function to get the number from a dataset string
# Turn the income bracket into a number so that it can be
#   easily manipulated

getYear <- function(string){
  p <- tail(str_split(string, "_")[[1]], 1)
  as.numeric(substring(p, 2))
}

# Use function to assign year data

tidy_data_numeric <- tidy_data %>% rowwise() %>% mutate(income_bracket = getYear(income_bracket))

#%>%mutate(income_bracket = getYear(income_bracket))

# Plot out data using the year to color

ggplot(tidy_data_numeric, aes(x = cohort, 
                      y = probability_exceed, 
                      group = income_bracket, 
                      col = income_bracket)) + 
  geom_line(size = .75, alpha = .1) + 
  geom_point(size = 2, alpha = .1) + 
  coord_cartesian(ylim = c(.0, 1.00)) +
  scale_y_continuous(labels = scales::percent) +
  scale_color_gradient(low = "green", high = "black")

# Save chart data to RDS file

write_rds(tidy_data_numeric, "./shiny/chart2.rds")

```


```{r}

### Chart 3 ###

# Plot key comparisons between income bracket groups
# I couldn't find any better what of getting specific groups
#   of income brackets so I just wrote them all out

spread_data <- tidy_data_numeric %>% select(cohort, income_bracket, probability_exceed) %>% 
  spread(key = income_bracket, value = probability_exceed) %>% 
  mutate(One = `1` - `100`, 
         Ten = (`1`+`2`+`4`+`5`+`6`+`7`+`8`+`9`+`10`)/10 - 
                 (`91`+`92`+`93`+`94`+`95`+`96`+`97`+`98`+`99`+`100`)/10,
        Fifty = (`1`+`2`+`3`+`4`+`5`+`6`+`7`+`8`+`9`+`10`+`11`+`12`+`13`+
                 `14`+`15`+`16`+`17`+`18`+`19`+`20`+`21`+`22`+`23`+`24`+`25`+
                 `26`+`27`+`28`+`29`+`30`+`31`+`32`+`33`+`34`+`35`+`36`+`37`+
                `38`+`39`+`40`+`41`+`42`+`43`+`44`+`45`+`46`+`47`+`48`+`49`+
                `50`)/50 + ( -`51`-`52`-`53`-`54`-`55`-`56`-`57`-`58`-`59`-`60`-`61`-`62`-
                `63`-`64`-`65`-`66`-`67`-`68`-`69`-`70`-`71`-`72`-`73`-`74`-`75`-
                `76`-`77`-`78`-`79`-`80`-`81`-`82`-`83`-`84`-`85`-`86`-`87`-`88`-
                `89`-`90`-`91`-`92`-`93`-`94`-`95`-`96`-`97`-`98`-`99`-`100`)/50) %>% 
  
  # Use select to choose the correct columns
  
  select(cohort, One:Fifty) %>% 
  
  # Use gather to put the data in a tidy format
  
  gather("Percentile", "data", One:Fifty) 


# Use ggplot to plot the spread data. Use color to split up the chart
#   by percentile

ggplot(spread_data, aes(x = cohort, y = data, color = Percentile)) + 
  geom_line(size = 2) +
  labs(title = "Disparities Between Percentage Chances of Earning More than Parents",
       y = "Dif. between top x percentile and bottom x percentile",
       x = "Year")

# Save chart data to RDS file

write_rds(spread_data, "./shiny/chart3.rds")

```


```{r}

### Chart 4 ###

# Use read_csv to read in the income inequality data from the file

inequality_data <- read_csv("data/Income_Inequality/data.csv")

# Use filter to examine the data regarding the top and bottom 10th percentiles
#   from the Chetty Dataset. Use mutate to change column names so that the 
#   left join of the two datasets is nice

filtered_spread_data <- spread_data %>% filter(Percentile == "Ten") %>% 
  mutate(year = cohort, percentage = data) %>% 
  select(year, percentage)

# Use left_join to join the inequality data and the american dream data 

spread_data2 <- left_join(filtered_spread_data, inequality_data, by = "year", suffix = c(".dif", ".inequality"))

# Use ggplot to plot the data. Use two geom_lines to plot
#   both of the different datasets, and use a scale_y_continous to
#   create a second axis

spread_data2 %>% 
  ggplot(aes(x = year)) + 
  geom_line(aes(y = percentage.dif, colour = "Top vs. Bottom 10% Disparity")) +
  geom_line(aes(y = percentage.inequality * 2.5, colour = "Wealth Held by Top 1%")) +
  scale_y_continuous(sec.axis = sec_axis(~./2.5, name = "% of Wealth Heald by top 1%")) +
  labs(title = "Disparities Between Top and Bottom 10th Percentile vs. Income Inequality",
       y = "Dif. between top 10% percentile and bottom 10% percentile",
       x = "Year")

# Save chart data to RDS file

write_rds(spread_data2, "./shiny/chart4.rds")

```

```{r}

# Use mutate to subtract 28 years from the dataset
#   we do this to adjust the inequality data for adulthood.
#   I.e. we want the inequality data for a given year to 
#   reflect the inequality a child born that year will 
#   experiece as an adult

inequality_data2 <- inequality_data %>% 
  mutate(year = year - 28)

# Use left join to join the new inequality dataset and 
#   the american dream data

spread_data3 <- left_join(filtered_spread_data, inequality_data2, by = "year", suffix = c(".dif", ".inequality"))

# Use the same ggplot command from the last code chunk to display the code

spread_data3 %>% 
  ggplot(aes(x = year)) + 
  geom_line(aes(y = percentage.dif, colour = "Top vs. Bottom 10% Disparity")) +
  geom_line(aes(y = percentage.inequality * 2.5, colour = "Wealth Held by Top 1%")) +
  scale_y_continuous(sec.axis = sec_axis(~./2.5, name = "% of Wealth Heald by top 1%")) +
  labs(title = "Disparities Between Top and Bottom 10th Percentile vs. Income Inequality",
       y = "Dif. between top 10% percentile and bottom 10% percentile",
       x = "Year")

# Save chart data to RDS file

write_rds(spread_data3, "./shiny/chart5.rds")

```

```{r}

### CHART 6 ###

# Use mutate and select to prepare american dream data for a left_join

simple_plot_new <- simple_plot %>% mutate(year = cohort,
                                          percentage = cohort_mean) %>% 
  select(year, percentage)

# Use left_join to join the 1% data and the inequality data

spread_data4 <- left_join(simple_plot_new, inequality_data, by = "year", suffix = c(".simple", ".inequality"))

# Use ggplot to plot the percentage of children earning more
#   than their parents vs. the wealth held by the top 1%
# We once again use scale_y_continous to add a second axis
# We also use theme to style the chart

ggplot(spread_data4, aes(x = year)) +
  geom_line(aes(y = percentage.simple, colour = "Pct. of Children Earning More than their Parents"), size = .75) +
  geom_point(aes(y = percentage.simple, colour = "Pct. of Children Earning More than their Parents"), size = 1.5) +
  geom_line(aes(y = percentage.inequality * 6, colour = "Wealth Held by Top 1%"), size = .75) +
  geom_point(aes(y = percentage.inequality * 6, colour = "Wealth Held by Top 1%"), size = 1.5) +
  scale_y_continuous(sec.axis = sec_axis(~./6, name = "% of Wealth Heald by top 1%")) +
  labs(title = "Disparities Between Top and Bottom 10th Percentile vs. Income Inequality",
       y = "Dif. between top 10% percentile and bottom 10% percentile",
       x = "Year") +
  theme_bw() +
  theme(axis.title.x = element_text(colour = "#9d9eac"),
        axis.title.y = element_text(colour = "#9d9eac")) +
  theme(legend.position="bottom")

# Save chart data to RDS file

write_rds(spread_data4, "./shiny/chart6.rds")

```

```{r}

### CHART 7 ###

# Use left_join to join the american dream data with the inequality
#   data that has been modified in order to account for age of adulthood

spread_data5 <- left_join(simple_plot_new, inequality_data2, by = "year", suffix = c(".simple", ".inequality"))

# Use the same ggplot command from the last code chunk to output the new graph

ggplot(spread_data5, aes(x = year)) +
  geom_line(aes(y = percentage.simple, colour = "Pct. of Children Earning More than their Parents"), size = .75) +
  geom_point(aes(y = percentage.simple, colour = "Pct. of Children Earning More than their Parents"), size = 1.5) +
  geom_line(aes(y = percentage.inequality * 4, colour = "Wealth Held by Top 1%"), size = .75) +
  geom_point(aes(y = percentage.inequality * 4, colour = "Wealth Held by Top 1%"), size = 1.5) +
  scale_y_continuous(sec.axis = sec_axis(~./4, name = "% of Wealth Heald by top 1%")) +
  labs(title = "Disparities Between Top and Bottom 10th Percentile vs. Income Inequality",
       y = "Dif. between top 10% percentile and bottom 10% percentile",
       x = "Year") +
  theme_bw() +
  theme(axis.title.x = element_text(colour = "#9d9eac"),
        axis.title.y = element_text(colour = "#9d9eac")) +
  theme(legend.position="bottom")

# Save chart data to RDS file

write_rds(spread_data5, "./shiny/chart7.rds")

```

```{r}

### AMERICAN STATE SHINY APP PLOT ###

# Load required libraries for the map plot

# Took inspiration from http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html

library(maps)
library(mapdata)
library(openintro)

# Use read_csv to load American Dream location data

baseline_estimates <- read_csv("data/state_data.csv") %>% 
  mutate(region = tolower(abbr2state(state_name)))

# Use the mapdata library to load data for state locations

states <- map_data("state")

# Use inner_join to join the america dream state data with the states
#   data in order to properly color the map

joined_state <- inner_join(states, baseline_estimates, by = "region")

# Create a theme that eliminates whitespace around the map and properly
#   colors it in

ditch_the_axes <- theme(
  axis.text = element_blank(),
  axis.line = element_blank(),
  axis.ticks = element_blank(),
  panel.border = element_blank(),
  panel.grid = element_blank(),
  axis.title = element_blank(),
  panel.background = element_rect(fill = "#ecf0f5"),
  plot.background = element_rect(fill = "#ecf0f5"),
  legend.background = element_rect(fill = "#ecf0f5")
)

# User filter to select a current year for the state data
#   this will be made automatic in the shiny app, but here
#   it is static
# Use geom_polygon to plot out the map
# Use the theme we made to style the map
# Use scale_fill_gradientn to properly color the map in a way
#    that it has both constant bounds on its colors and also
#    allows the user to clearly see the value

joined_state %>% filter(cohort == 1950) %>% 
ggplot() + 
  geom_polygon(aes(x = long, y = lat, fill = cohort_mean, group = group), color = "white") + 
  coord_fixed(1.3) +
  ditch_the_axes +
  scale_fill_gradientn(colours = c("#ce2828", "#7a2416", "#14254f", "#1e6612", "#41ce28"),
                       limits = c(.3,1))


# Save data to RDS file

write_rds(joined_state, "./shiny/chart8.rds")

```




